#!/bin/bash
dirs=$@
if [ "$dirs" == "" ]
then
    dirs="."
fi
base=$(pwd)
for dir in $dirs
do
    for f in $(find $dir -type d -name .git)
    do
       echo "----------$f---------------"
       cd $f && cd .. && git pull
       cd $base
    done
done
